ShortURL/ShortURL/Controllers/TrackclicksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShortURL.Helpers;
using ShortURL.Models;

namespace ShortURL.Controllers
{
    public class TrackclicksController : Controller
    {
        // GET: Trackclicks
        public ActionResult Index(string u)
        {
            try
            {
                if (!string.IsNullOrEmpty(u))
                {
                    URLInfo info = new URLInfo();
                    Uri uri = new Uri(u);
                    ProcessURLController processURL = new ProcessURLController();
                    info = processURL.GetURLInfo(uri.AbsolutePath.TrimStart('/'), false);

                    return View(info);
                }
                else
                {
                    return View();
                }
            }
            catch(Exception ex)
            {
                ServiceLocator.ErrorLogger("NEW ERROR LINE : Trackclicks/Index | " + DateTime.Now + " | Error:  " + ex.ToString());

                return View();
            }
            
           
        }

        
    }
}

ShortURL/ShortURL/Controllers/URLShortnerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ShortURL.Helpers;
using ShortURL.Models;

namespace ShortURL.Controllers
{
    public class URLShortnerController : Controller
    {
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(URLInfo urlInfo)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    HttpResponseMessage response = new HttpResponseMessage();
                    if (string.IsNullOrEmpty(urlInfo.LongURL))
                    {
                        return View();
                    }
                    else
                    {
                        ProcessURLController processURL = new ProcessURLController();
                        response = processURL.ShortenURL(urlInfo);


                        return View(urlInfo);
                    }
                }

                return View(urlInfo);
                

            }
            catch (Exception ex)
            {
                ServiceLocator.ErrorLogger("NEW ERROR LINE : URLShortner/Index | " + DateTime.Now + " | Error:  " + ex.ToString());

                return View();                               
            }
        }

        [HttpGet]
        public ActionResult RedirectToURL(string shortCode)
        {
            try
            {
                URLInfo info = new URLInfo();
                ProcessURLController processURL = new ProcessURLController();
                info = processURL.GetURLInfo(shortCode, true);

                if (info != null && !string.IsNullOrEmpty(info.LongURL))
                {
                    return Redirect(info.LongURL);
                }
                else
                {
                    return Redirect(ConfigurationManager.AppSettings["redirecturl"].ToString());
                }
            }
            catch(Exception ex)
            {
                ServiceLocator.ErrorLogger("NEW ERROR LINE : URLShortner/RedirectToURL | " + DateTime.Now + " | Error:  " + ex.ToString());

                return Redirect(ConfigurationManager.AppSettings["redirecturl"].ToString());
            }
            

        }
                        
    }
}

ShortURL/ShortURL/Views/Trackclicks/Index.cshtml
@model ShortURL.Models.URLInfo
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_URLShortLayout.cshtml";
}

<!DOCTYPE html>


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>URL Shortner</title>

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-ui.min.js"></script>



</head>

<body>

    <div class="container-fluid">
        <div class="row" style="padding-top:80px">
            <div class="col-md-6" style="padding-left:30px; color:#428bca; font-weight:normal">
                @Html.Label("Long URL Info and Click Count")
            </div>

            <div class="col-md-12" style="text-align:right; padding-right:30px">
                @Html.ActionLink("URL Shortner", "Index", "URLShortner")
            </div>
        </div>
    </div>



    <div class="container body-content" style="padding-top:30px; margin-left:30px">


        @using (Html.BeginForm("Index", "Trackclicks", FormMethod.Post))
        {
            <div class="row">
                <div class="col-md-12">
                    <label>Short URL: </label>
                    @Html.TextBox("u",ViewBag.u as string , new { style = "width:500px;", @id = "txtLongURL" })
                </div>
                @*<div class="input-group mb-2 mb-sm-0">
                        <div class="col-md-12">
                            <label>Long URL: </label>
                            @Html.TextBoxFor(x => x.LongURL, new { @class = "form-control", @id = "txtInvoiceId" })
                        </div>


                    </div>*@

            </div>
            <div class="clearfix"></div>
            <div class="row" style="margin-top:15px;">
                <div class="col-md-3">

                    <div class="input-group mb-2 mb-sm-0">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>


            </div>

        }

        @if (Model != null)
        {
            <div class="row" style="padding-top:30px">

                @if (Model.ShortURL != null && Model.ShortURL != "")
                {
                    
                    <div class="col-md-12">
                        <label>Clicks Count: </label>
                        @Html.Label(Model.ClicksCount.ToString(), new { @class = "form-control" })

                    </div>

                    <div class="col-md-12" >
                        <label>Long URL: </label>
                    </div>
                    <div class="col-md-12" style="overflow:auto;">
                        @Html.LabelFor(model => model.LongURL, String.Format("{0}", @Model.LongURL.ToString()))

                    </div>
                }
                else
                {
                    <div class="col-md-12">
                        <b>No Details Found.</b>
                    </div>
                }



            </div>
        }


    </div>



</body>
</html>